add_newline = true
format = '''
[  ](#f38ba8)$username$directory$git_branch$git_status$package
$character'''

right_format = """$all$aws$conda$dart$c$cmake$elixir$golang$java$jlua$lua$nodejs$perl$php$python$ruby$rust$swift$cmd_duration"""

[directory]
style = "#fab387"
format = "[$path]($style) "
truncation_length = 4

[hostname]
ssh_symbol = " "
format = "[$ssh_symbol $hostname]($style) "

[git_branch]
symbol = " "
format =  "[$symbol $branch (:$remote_branch)]($style)"

[git_status]
style = "bold green"
format = "[$modified$deleted$untracked$ahead_behind]($style) "
modified = " "
deleted = " "
untracked = " "
ahead = " "
behind = " "
up_to_date = " "

[cmd_duration]
min_time = 1_000
style = "bold red"
format = "[$duration]($style)"

[sudo]
style = "bold white"
format = "[$symbol]($style) "
symbol = " "
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold pink)'
error_symbol = '[❯](bold red)'
#[❯❯ ](bold green)

[aws]
symbol = "  "
style = "fg:#d99e29"
format = '[ $symbol ($version )]($style)'

[conda]
symbol = " "
style = "fg:#cba6f7"
format = '[ $symbol ($version )]($style)'

[dart]
symbol = " "
style = "fg:#29d9aa"
format = '[ $symbol ($version )]($style)'

[c]
symbol = " "
style = "fg:#2958d9"
format = '[ $symbol ($version )]($style)'

[cmake]
symbol = "󰔷 "
style = "fg:#2958d9"
format = '[ $symbol ($version )]($style)'

[docker_context]
symbol = " "
style = "fg:#0d339e"
format = '[ $symbol $context]($style) $path '

[elixir]
symbol = " "
style = "fg:#440d9e"
format = '[ $symbol ($version )]($style)'

[elm]
symbol = " "
style = "fg:#8623b8"
format = '[ $symbol ($version )]($style)'

[golang]
symbol = " "
style = "fg:#4991e3"
format = '[ $symbol ($version )]($style)'

[haskell]
symbol = "λ"
style = "fg:#9348d9"
format = '[ $symbol ($version )]($style)'

[java]
symbol = " "
style = "fg:#db2332"
format = '[ $symbol ($version )]($style)'

[julia]
symbol = " "
style = "fg:#cba6f7"
format = '[ $symbol ($version )]($style)'

[lua]
symbol = " "
style = "fg:#cba6f7"
format = '[ $symbol ($version )]($style)'

[nim]
symbol = " "
style = "fg:#cba6f7"
format = '[ $symbol ($version )]($style)'

[nodejs]
symbol = "  "
style = "fg:#018c42"
format = '[ $symbol ($version )]($style)'

[perl]
symbol = " "
style = "fg:#cba6f7"
format = '[ $symbol ($version )]($style)'

[php]
symbol = " "
style = "fg:#cba6f7"
format = '[ $symbol ($version )]($style)'

[python]
symbol = " "
style = "fg:#ede245"
format = '[ $symbol ($version )]($style)'

[ruby]
symbol = " "
style = "fg:#780905"
format = '[ $symbol ($version )]($style)'

[rust]
symbol = " "
style = "fg:#bd4e26"
format = '[ $symbol ($version )]($style)'

[swift]
symbol = " "
style = "fg:#cba6f7"
format = '[ $symbol ($version )]($style)'

[package]
symbol = " "
style = "fg:#cba6f7"
format = "[ $symbol $version]($style)"
disabled = true

